<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EdpMarkdown\Module'               => __DIR__ . '/Module.php',
    'EdpMarkdown\View\Helper\Markdown' => __DIR__ . '/src/EdpMarkdown/View/Helper/Markdown.php',
    'Textile'                          => __DIR__ . '/src/PhpMarkdown/markdown.php',
    'Markdown_Parser'                  => __DIR__ . '/src/PhpMarkdown/markdown.php',
    'MarkdownExtra_Parser'             => __DIR__ . '/src/PhpMarkdown/markdown.php',
);
